# Generated by Django 4.1 on 2022-09-02 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pessoas_pessoa_idade_alter_pessoas_pessoa_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_nome', models.CharField(max_length=40)),
                ('ativo', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'ordering': ('pessoa_nome', 'pessoa_idade')},
        ),
        migrations.AddField(
            model_name='pessoas',
            name='PessoaCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='TimeStamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoas',
            name='pessoa_ativo',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('pessoas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.pessoas')),
                ('AlunoCreate', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('codigo_aluno', models.CharField(max_length=10, null=True)),
                ('Alunos_data', models.DateField()),
                ('Media_Geral_Inteiro', models.IntegerField()),
                ('tipo', models.CharField(choices=[('P', 'Particular'), ('C', 'Convenio')], max_length=1)),
                ('aluno_ativo', models.CharField(default='S', max_length=1)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.turmas')),
            ],
            bases=('app1.pessoas',),
        ),
    ]
