

BEGIN TRANSACTION;

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CPF TEXT NOT NULL,
    NOME TEXT NOT NULL,
    IDADE INT NOT NULL,
    ENDERECO CHAR(50),
    CIDADE TEXT,
    SALARIO REAL
);

COMMIT;

BEGIN TRANSACTION;

INSERT INTO PESSOAS (CPF, NOME, IDADE, ENDERECO, CIDADE, SALARIO)
    VALUES 
    ('123.456.789.10', 'Rogério', 20, 'Rua Francisco Cândido Xavier', 'Floripa', 88066.027),
    ('123.456.789.10', 'Rogério2', 21, 'Rua Francisco Cândido Xavier', 'Floripa', 88066.027);
COMMIT;