-- testesmd4.sql

\
DROP TABLE IF EXISTS CIDADES;


CREATE TABLE CIDADES(
    CIDADES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADES_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS(
    PESSOAS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOAS_NOME TEXT NOT NULL,
    PESSOAS_IDADE INTEGER,
    PESSOAS_CIDADES_ID INTEGER NOT NULL
);

INSERT INTO CIDADES (CIDADES_NOME)
    VALUES
    ('RIO NEGRINHO'),
    ('FLORIPA'),
    ('JOINVILLE'),
    ('PORTO ALEGRE');

INSERT INTO PESSOAS(PESSOAS_NOME, PESSOAS_IDADE, PESSOAS_CIDADES_ID)
    VALUES
    ('Rogério Hanke', 20, 2),
    ('Marina', 21, 4),
    ('Jéssica', 22, 1);
COMMIT;

