

BEGIN TRANSACTION;

DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE PRODUTOS(
    PRODUTOS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUTOS_NOME TEXT NOT NULL,
    PRODUTOS_VALOR TEXT NOT NULL,
    PRODUTOS_LOCAL INTEGER 
);

DROP TABLE IF EXISTS ATENDENTES;

CREATE TABLE ATENDENTES(
    ATENDENTES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ATENDENTES_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES(
    CLIENTES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CLIENTES_NOME TEXT NOT NULL,
    CLIENTES_FONE TEXT NOT NULL,
    CLIENTES_CPF INTEGER,
    CLIENTES_TOTALDECOMPRAS INTEGER --ITENS_VALORTOTAL
);

DROP TABLE IF EXISTS PRATELEIRAS;

CREATE TABLE PRATELEIRAS(
    PRATELEIRAS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRATELEIRAS_NOME TEXT NOT NULL,
    PRATELEIRAS_LOCAL TEXT NOT NULL
);

DROP TABLE IF EXISTS ITENS_NOTA;

CREATE TABLE ITENS_NOTA(
    ITENS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITENS_SEQUENCIA INTEGER,
    ITENS_PRODUTO TEXT NOT NULL, --PRODUTOS_NOME_ID
    ITENS_NUMERONOTA INTEGER,
    ITENS_QUANTIDADE INTEGER,
    ITENS_VALORUNID TEXT NOT NULL,
    ITENS_VALORTOTAL TEXT NOT NULL
);

DROP TABLE IF EXISTS NOTA_FISCAL;

CREATE TABLE NOTA_FISCAL( 
    NOTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTA_DATA DATETIME DEFAULT CURRENT_TIMESTAMP,
    NOTA_NUM INTEGER,
    NOTA_CLIENTES INTEGER, --CLIENTES_ID
    NOTA_ATENDENTES INTEGER --ATENDENTES_ID
);

COMMIT;

